<aside class="app-sidebar">
<!--
    <div class="app-sidebar__user">
        <div class="dropdown">
            <a class="nav-link pl-2 pr-2 leading-none d-flex" data-toggle="dropdown" href="#">
                <img alt="image" src="assets/img/avatar/avatar-1.jpeg" class=" avatar-md rounded-circle">
                <span class="ml-2 d-lg-block">
                    <span class=" app-sidebar__user-name mt-5">Jessica Lee</span><br>
                    <span class="text-muted app-sidebar__user-name text-sm"> Web-Designer</span>
                </span>
            </a>
        </div>
    </div>
-->
<br>
    <ul class="side-menu">
        <li class="slide">
            <a class="side-menu__item" href="home.php">
                <i class="side-menu__icon fa fa-home"></i>
                <span class="side-menu__label">H O M E</span></a>
        </li>
     
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-group"></i><span class="side-menu__label">ADMINISTRATION</span><i class="angle fa fa-angle-right"></i></a>
            <ul class="slide-menu">

                <li>
                    <a href="pages.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Page Introduction
                    </a>
                </li>
                
                <li>
                    <a href="facilities.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Facilities
                    </a>
                </li>
                
                <li>
                    <a href="news.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        News
                    </a>
                </li>

                <li>
                    <a href="announcements.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Announcement
                    </a>
                </li>

                <li>
                    <a href="events.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Events and Photos
                    </a>
                </li>

                <li>
                    <a href="gallery.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Gallery
                    </a>
                </li>
<!-- 
                <li>
                    <a href="papers.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Downloads
                    </a>
                </li>
                 -->
                <li>
                    <a href="users.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        User Accounts
                    </a>
                </li>

            </ul>
        </li>

             
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-group"></i><span class="side-menu__label">RESEARCH</span><i class="angle fa fa-angle-right"></i></a>

            <ul class="slide-menu">

                <li>
                    <a href="researchprops.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Projects
                    </a>
                </li>
                <li>
                    <a href="lectures.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Lecture Series
                    </a>
                </li>
                
            </ul>

        </li>

             
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-group"></i><span class="side-menu__label">LIBRARY</span><i class="angle fa fa-angle-right"></i></a>

            <ul class="slide-menu">

                <li>
                    <a href="#" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Books
                    </a>
                </li>
                
                <li>
                    <a href="#" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Journals
                    </a>
                </li>
                
                <li>
                    <a href="#" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Newspapers and Articles
                    </a>
                </li>
                
            </ul>

        </li>

             
        <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#"><i class="side-menu__icon fa fa-group"></i><span class="side-menu__label">TRAINING</span><i class="angle fa fa-angle-right"></i></a>

            <ul class="slide-menu">

                <li>
                    <a href="training_units.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Training Units
                    </a>
                </li>
                
                <li>
                    <a href="#" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Course Types
                    </a>
                </li>
                                
                <li>
                    <a href="courses.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Courses
                    </a>
                </li>
          
                <li>
                    <a href="tr_schdl.php" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Training Calendar
                    </a>
                </li>
          
                <li>
                    <a href="#" class="slide-item">
                        <i class="side-menu__icon fa fa-user-secret"></i>
                        Profile of Trainers
                    </a>
                </li>

            </ul>

        </li>
       <li class="slide">
            <a class="side-menu__item" data-toggle="slide" href="#">
                <i class="side-menu__icon fa fa-eye"></i>
                <span class="side-menu__label">AUDIT TRAIL</span>
            </a>
        </li>
    </ul>
</aside>