<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="Academy, EFCC, EFCC Academy, TRI">
<meta name="author" content="Braun Okoi Boniface, Akilu Y. Umar">

<!--Favicon -->
<link rel="icon" href="assets/img/alms.png" type="image/x-icon"/>

<!--Bootstrap.min css-->
<link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css">

<!--Icons css-->
<link rel="stylesheet" href="assets/css/icons.css">

<!--Style css-->
<link rel="stylesheet" href="assets/css/style.css">

<!--mCustomScrollbar css-->
<link rel="stylesheet" href="assets/plugins/scroll-bar/jquery.mCustomScrollbar.css">

<!--Sidemenu css-->
<link rel="stylesheet" href="assets/plugins/toggle-menu/sidemenu.css">

<!-- Datatables css -->
<link rel="stylesheet" href="assets/plugins/Datatable/css/dataTables.bootstrap4.css">

<!--Chartist css-->
<!--<link rel="stylesheet" href="assets/plugins/chartist/chartist.css">-->
<!--<link rel="stylesheet" href="assets/plugins/chartist/chartist-plugin-tooltip.css">-->

<!--Full calendar css-->
<link rel="stylesheet" href="assets/plugins/fullcalendar/stylesheet1.css">

<!--morris css-->
<!--<link rel="stylesheet" href="assets/plugins/morris/morris.css">-->

<!-- Select2 css-->
<link rel="stylesheet" href="assets/plugins/select2/select2.css">

<!-- iCheck css-->
<link rel="stylesheet" href="assets/plugins/iCheck/all.css">

<link rel="stylesheet" href="assets/css/croppie.css">

<!-- App css-->
<link href="assets/css/app.css" rel="stylesheet">

<script src="vendors/tinymce/js/tinymce/tinymce.min.js"></script>
