<!--Jquery.min js-->
<script src="assets/js/jquery.min.js"></script>

<!--popper js-->
<script src="assets/js/popper.js"></script>

<!--Tooltip js-->
<script src="assets/js/tooltip.js"></script>

<!--Bootstrap.min js-->
<script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>

<!--Jquery.nicescroll.min js-->
<script src="assets/plugins/nicescroll/jquery.nicescroll.min.js"></script>

<!--Scroll-up-bar.min js-->
<script src="assets/plugins/scroll-up-bar/dist/scroll-up-bar.min.js"></script>

<!--Sidemenu js-->
<script src="assets/plugins/toggle-menu/sidemenu.js"></script>

<!--mCustomScrollbar js-->
<script src="assets/plugins/scroll-bar/jquery.mCustomScrollbar.concat.min.js"></script>

<!-- jQuery Sparklines -->
<!--<script src="assets/plugins/jquery-sparkline/dist/jquery.sparkline.js"></script>-->

<!-- ECharts -->
<!--<script src="assets/plugins/echarts/dist/echarts.js"></script>-->

<!--Jquery.knob js-->
<!--
<script src="assets/plugins/othercharts/jquery.knob.js"></script>
<script src="assets/plugins/othercharts/jquery.sparkline.min.js"></script>
-->

<!--Morris js-->
<!--
<script src="assets/plugins/morris/morris.min.js"></script>
<script src="assets/plugins/morris/raphael.min.js"></script>
-->

<!-- Datatables js-->
<script src="assets/plugins/Datatable/js/jquery.dataTables.js"></script>
<script src="assets/plugins/Datatable/js/dataTables.bootstrap4.js"></script>

<!-- Select2 js-->
<script src="assets/plugins/select2/select2.full.js"></script>

<!--Scripts js-->
<script src="assets/js/scripts.js"></script>

<!-- iCheck js-->
<script src="assets/plugins/iCheck/icheck.min.js"></script>

<!--Dashboard js-->
<script src="assets/js/forms.js"></script>
<!--<script src="assets/js/dashboard.js"></script>-->
<!--
<script src="assets/js/sparkline.js"></script>
<script src="assets/js/apexcharts.js"></script>
-->
<script src="assets/js/croppie.min.js"></script>
<script src="assets/js/app.js"></script>
<script>
    $(function() {
        $('textarea').on('focus', function() {
            tinymce.init({
                selector:'textarea',
                plugins: 'print preview fullpage powerpaste casechange importcss tinydrive searchreplace autolink autosave save directionality advcode visualblocks visualchars fullscreen image link media mediaembed template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists checklist wordcount tinymcespellchecker a11ychecker imagetools textpattern noneditable help formatpainter permanentpen pageembed charmap tinycomments mentions quickbars linkchecker emoticons',
                menubar: 'file edit view insert format tools table help',
                toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | a11ycheck ltr rtl | showcomments addcomment'
            });
        });
    });
</script>